import { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { useAuth } from './AuthContext';

type Language = 'fr' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateFeature: (feature: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'app.name': 'HELLOFONTY',
    'app.tagline': 'Logements gratuits pour étudiants INSEAD à Fontainebleau',
    'nav.home': 'Accueil',
    'nav.search': 'Rechercher',
    'nav.favorites': 'Favoris',
    'nav.messages': 'Messages',
    'nav.myListings': 'Mes annonces',
    'nav.addListing': 'Ajouter une annonce',
    'nav.profile': 'Profil',
    'nav.signIn': 'Connexion',
    'nav.signUp': 'Inscription',
    'nav.signOut': 'Déconnexion',
    'auth.signIn': 'Connexion',
    'auth.signUp': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.phone': 'Téléphone',
    'auth.role': 'Je suis',
    'auth.student': 'Étudiant INSEAD',
    'auth.landlord': 'Propriétaire',
    'auth.alreadyAccount': 'Déjà un compte ?',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.signInButton': 'Se connecter',
    'auth.signUpButton': "S'inscrire",
    'auth.verification': 'Vérification INSEAD',
    'auth.uploadDocument': 'Télécharger attestation de scolarité (PDF)',
    'auth.pendingVerification': 'En attente de vérification',
    'auth.verified': 'Compte vérifié',
    'home.hero.title': 'Trouvez votre logement à Fontainebleau',
    'home.hero.subtitle': 'Plateforme réservée aux étudiants INSEAD',
    'home.hero.verified': 'Logements vérifiés pour étudiants INSEAD Fontainebleau',
    'nav.pricing': 'Tarifs',
    'nav.myBookingRequests': 'Mes demandes',
    'home.hero.cta': 'Commencer la recherche',
    'home.students.title': 'Trouvez le logement parfait à Fontainebleau',
    'home.landlords.title': 'Trouvez vos locataires INSEAD',
    'home.cta.title': 'Prêt à commencer ?',
    'home.cta.subtitle': 'Rejoignez la communauté HELLOFONTY aujourd’hui',
    'home.secureplatform': 'Plateforme 100% sécurisée réservée exclusivement aux étudiants INSEAD Fontainebleau',
    'home.featured.title': 'Logements disponibles',
    'home.featured.subtitle': 'Découvrez les dernières annonces à Fontainebleau',
    'home.map.title': 'Explorez Fontainebleau',
    'home.map.subtitle': 'Découvrez l’emplacement de tous nos logements disponibles',
    'home.howItWorks': 'Comment ça marche',
    'home.forStudents': 'Pour les étudiants',
    'home.forStudents.desc': 'Inscrivez-vous avec votre attestation INSEAD, recherchez des logements et contactez directement les propriétaires',
    'home.step1': 'Inscrivez-vous en 30 secondes',
    'home.step2': 'Téléchargez votre attestation de scolarité',
    'home.step3': 'Recherchez des logements vérifiés',
    'home.step4': 'Contactez directement les propriétaires',
    'home.step5': 'Réservez votre logement idéal',
    'home.forLandlords': 'Pour les propriétaires',
    'home.forLandlords.desc': 'Trouvez des étudiants INSEAD avec profil vérifié rapidement et gratuitement',
    'home.features': 'Fonctionnalités',
    'home.feature.verified': 'Communauté vérifiée',
    'home.feature.verified.desc': 'Accès réservé aux étudiants INSEAD vérifiés',
    'home.feature.free': 'Logements 100% vérifiés',
    'home.feature.free.desc': 'Réservé exclusivement aux étudiants INSEAD vérifiés',
    'home.feature.secure': 'Paiements sécurisés',
    'home.feature.secure.desc': 'Tous les logements sont vérifiés et les paiements sont 100% sécurisés',
    'home.feature.direct': 'Contact direct',
    'home.feature.direct.desc': 'Messagerie intégrée pour échanger facilement',
    'search.title': 'Rechercher un logement',
    'search.filters': 'Filtres',
    'search.city': 'Ville',
    'search.propertyType': 'Type de bien',
    'search.propertyType.all': 'Tous',
    'search.propertyType.apartment': 'Appartement',
    'search.propertyType.house': 'Maison',
    'search.propertyType.room': 'Chambre',
    'search.propertyType.option.all': 'Tous types',
    'search.propertyType.option.room': 'Chambre',
    'search.propertyType.option.apartment': 'Appartement',
    'search.propertyType.option.house': 'Maison',
    'search.propertyType.option.studio': 'Studio',
    'search.priceRange': 'Prix maximum (€/mois)',
    'search.bedrooms': 'Chambres min.',
    'search.guests': 'Personnes',
    'search.propertyTypeLabel': 'Type de logement',
    'search.checkIn': 'Arrivée',
    'search.checkOut': 'Départ',
    'search.guestsLabel': 'Voyageurs',
    'search.searchButton': 'Rechercher',
    'search.searchPlaceholder': 'Rechercher un logement...',
    'search.checkInPlaceholder': 'Date d\'arrivée',
    'search.checkOutPlaceholder': 'Date de départ',
    'search.guestSingular': 'voyageur',
    'search.guestPlural': 'voyageurs',
    'search.results': 'résultats',
    'search.noResults': 'Aucun résultat trouvé',
    'listing.perMonth': '/mois',
    'listing.bedrooms': 'chambres',
    'listing.bathrooms': 'salles de bain',
    'listing.guests': 'personnes max',
    'listing.details': 'Détails',
    'listing.amenities': 'Équipements',
    'listing.availability': 'Disponibilités',
    'listing.location': 'Localisation',
    'listing.available': 'disponibles',
    'listing.availableSingular': 'disponible',
    'listing.singular': 'logement',
    'listing.plural': 'logements',
    'listing.contact': 'Contacter le propriétaire',
    'listing.bookingRequest': 'Envoyer une demande de réservation',
    'listing.signInToBook': 'Se connecter pour réserver',
    'listing.addToFavorites': 'Ajouter aux favoris',
    'listing.removeFromFavorites': 'Retirer des favoris',
    'listing.owner': 'Votre hôte',
    'listing.reviews': 'avis',
    'listing.listings': 'annonces',
    'listing.listing': 'annonce',
    'listing.memberSince': 'Membre depuis',
    'listing.superhost': 'Superhôte',
    'listing.verified': 'Identité vérifiée',
    'listing.defaultBio': "Hôte expérimenté passionné par l'accueil et le confort des étudiants. Toujours disponible pour répondre à vos questions et vous aider dans votre recherche de logement.",
    'listing.houseRules': 'Règles de la maison',
    'favorites.title': 'Mes favoris',
    'favorites.empty': 'Aucun favori enregistré',
    'messages.title': 'Messages',
    'messages.conversations': 'Conversations',
    'messages.empty': 'Aucun message',
    'messages.send': 'Envoyer',
    'messages.typeMessage': 'Tapez votre message...',
    'messages.contactAllowed': 'Réservation confirmée : vous pouvez échanger vos coordonnées en toute sécurité.',
    'messages.blocked.title': 'Attention - Communication en direct interdite',
    'messages.blocked.attemptWarning': 'Tentative {count} - Risque de bannissement !',
    'messages.blocked.why': 'Pourquoi cette restriction ?',
    'messages.blocked.whyText': "Nous avons détecté dans votre message des informations de contact (téléphone, email, réseaux sociaux, etc.). Pour votre sécurité et celle de tous les utilisateurs, les échanges directs hors plateforme sont interdits avant confirmation et paiement de la réservation.",
    'messages.blocked.risksTitle': 'Les risques de passer en direct :',
    'messages.blocked.risk.ban': 'Risque de bannissement',
    'messages.blocked.risk.banDesc': 'Votre compte peut être suspendu ou définitivement banni',
    'messages.blocked.risk.scams': 'Fausses annonces et arnaques',
    'messages.blocked.risk.scamsDesc': "Impossibilité de vérifier l'authenticité sans notre contrôle",
    'messages.blocked.risk.noProtection': 'Aucune protection',
    'messages.blocked.risk.noProtectionDesc': 'Aucune assurance, aucun recours en cas de problème',
    'messages.blocked.risk.noSupport': 'Aucun SAV ni support',
    'messages.blocked.risk.noSupportDesc': 'Notre équipe ne pourra pas vous aider en cas de litige',
    'messages.blocked.afterPayment': 'Après confirmation et paiement',
    'messages.blocked.afterPaymentText': 'Une fois votre réservation confirmée et payée, vous pourrez librement échanger vos coordonnées avec votre interlocuteur en toute sécurité.',
    'messages.blocked.modify': 'Modifier mon message',
    'messages.blocked.understand': "J'ai compris",
    'admin.alerts.title': 'Tentatives Bloquées',
    'admin.alerts.last7days': '7 derniers jours',
    'admin.alerts.last30days': '30 derniers jours',
    'admin.alerts.usersAtRisk': 'Utilisateurs à risque',
    'admin.alerts.attemptsBlocked': 'Tentatives bloquées',
    'admin.alerts.totalAttempts': 'Total tentatives',
    'admin.alerts.mainType': 'Type principal',
    'admin.alerts.mostFrequent': 'Plus fréquent',
    'admin.alerts.allTypes': 'Tous types',
    'admin.alerts.dateTime': 'Date/Heure',
    'admin.alerts.user': 'Utilisateur',
    'admin.alerts.recipient': 'Destinataire',
    'admin.alerts.type': 'Type',
    'admin.alerts.excerpt': 'Extrait',
    'admin.alerts.attempts': 'Tentatives',
    'admin.alerts.actions': 'Actions',
    'admin.alerts.details': 'Détails',
    'admin.alerts.noAttempts': 'Aucune tentative bloquée',
    'admin.alerts.noAttemptsDesc': 'Les tentatives de contournement apparaîtront ici',
    'admin.alerts.detailsTitle': 'Détails de la Tentative Bloquée',
    'admin.alerts.totalAttempts30': 'tentative(s) au total (30 derniers jours)',
    'admin.alerts.blockedContent': 'Contenu Bloqué',
    'admin.alerts.detectedPatterns': 'Patterns Détectés',
    'admin.alerts.userAtRiskTitle': 'Utilisateur à Risque',
    'admin.alerts.userAtRiskDesc': 'Cet utilisateur a effectué {count} tentatives de contournement dans les 30 derniers jours. Surveillance recommandée.',
    'admin.alerts.close': 'Fermer',
    'admin.alerts.dateType': 'Date & Type',
    'admin.alerts.conversations': 'Conversations',
    'admin.alerts.alertsTab': 'Alertes',
    'booking.accept': 'Accepter',
    'booking.decline': 'Refuser',
    'booking.contactTenant': 'Contacter le locataire',
    'booking.nights': 'nuits',
    'booking.night': 'nuit',
    'myListings.title': 'Mes annonces',
    'myListings.empty': 'Aucune annonce publiée',
    'myListings.add': 'Ajouter une annonce',
    'myListings.edit': 'Modifier',
    'myListings.delete': 'Supprimer',
    'addListing.title': 'Ajouter une annonce',
    'addListing.title.edit': 'Modifier l\'annonce',
    'addListing.basicInfo': 'Informations générales',
    'addListing.title.label': 'Titre de l\'annonce',
    'addListing.description': 'Description',
    'addListing.propertyType': 'Type de bien',
    'addListing.location': 'Adresse et localisation',
    'addListing.address': 'Adresse complète',
    'addListing.city': 'Ville',
    'addListing.postalCode': 'Code postal',
    'addListing.details': 'Détails du logement',
    'addListing.price': 'Prix par mois (€)',
    'addListing.bedrooms': 'Nombre de chambres',
    'addListing.bathrooms': 'Nombre de salles de bain',
    'addListing.maxGuests': 'Nombre de personnes max',
    'addListing.amenities': 'Équipements',
    'addListing.photos': 'Photos',
    'addListing.uploadPhotos': 'Télécharger des photos',
    'addListing.submit': 'Publier l\'annonce',
    'addListing.update': 'Mettre à jour',
    'profile.title': 'Mon profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.language': 'Langue préférée',
    'profile.save': 'Enregistrer',
    'profile.verification': 'Vérification',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Opération réussie',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'footer.about': 'À propos',
    'footer.aboutDesc': 'HELLOFONTY est la plateforme de référence pour trouver votre logement étudiant à Fontainebleau.',
    'footer.quickLinks': 'Liens rapides',
    'footer.searchListing': 'Rechercher un logement',
    'footer.postListing': 'Publier une annonce',
    'footer.pricing': 'Tarifs',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.followUs': 'Suivez-nous',
    'footer.rights': 'Tous droits réservés',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.forgotPasswordTitle': 'Mot de passe oublié',
    'auth.forgotPasswordSubtitle': 'Entrez votre email pour recevoir un lien de réinitialisation',
    'auth.sendResetLink': 'Envoyer le lien',
    'auth.backToSignIn': 'Retour à la connexion',
    'auth.emailNotFound': 'Hmm... Cet email nous est inconnu ! Êtes-vous sûr d\'avoir un compte chez nous ? Sinon, c\'est le moment de nous rejoindre !',
    'auth.resetEmailSent': 'Email de réinitialisation envoyé avec succès ! Le mail peut prendre 2 à 3 minutes avant d\'arriver. N\'oubliez pas de vérifier vos spams !',
    'auth.sending': 'Envoi en cours...',
    'auth.resetPasswordTitle': 'Nouveau mot de passe',
    'auth.resetPasswordSubtitle': 'Choisissez un nouveau mot de passe sécurisé',
    'auth.newPassword': 'Nouveau mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.changePassword': 'Changer le mot de passe',
    'auth.updating': 'Mise à jour...',
    'auth.minCharacters': 'Minimum 6 caractères',
    'auth.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.passwordsNotMatch': 'Les mots de passe ne correspondent pas',
    'auth.passwordUpdated': 'Mot de passe mis à jour avec succès ! Redirection...',
    'auth.invalidResetLink': 'Lien de réinitialisation invalide ou expiré. Veuillez demander un nouveau lien.',
    'admin.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette annonce ?',
    'admin.deleteSuccess': 'Annonce supprimée avec succès !',
    'admin.deleteError': 'Erreur lors de la suppression de l\'annonce',
    'admin.allRoles': 'Tous les rôles',
    'admin.students': 'Étudiants',
    'admin.landlords': 'Propriétaires',
    'home.step.landlord.1': 'Créez votre compte propriétaire',
    'home.step.landlord.2': 'Publiez votre annonce avec photos',
    'home.step.landlord.3': 'Recevez des demandes d\'étudiants vérifiés',
    'home.step.landlord.4': 'Échangez directement via la messagerie',
    'home.step.landlord.5': 'Louez en toute confiance',
    'addListing.linens': 'Linge de maison (serviettes et draps)',
    'addListing.airbnbImport': 'Gagnez du temps ! Collez le lien de votre annonce Airbnb pour pré-remplir automatiquement les informations.',
    'addListing.publishSuccess': 'Votre annonce est maintenant en ligne et visible par tous les étudiants !',
    'myListings.confirmDuplicate': 'Dupliquer cette annonce ?',
    'myListings.duplicateSuccess': 'Annonce dupliquée avec succès !',
    'myDocuments.fileTypeError': 'Format de fichier non accepté. Utilisez PDF, JPG ou PNG',
    'myDocuments.leaseDescription': 'Le bail sera disponible ici une fois signé par toutes les parties',
    'navbar.landlordOnlyMessage': 'Vous devez avoir un compte propriétaire pour déposer une annonce.',
    'support.helpMessage': 'Nous sommes là pour vous aider',
    'support.roleQuestion': 'Vous êtes un étudiant ou un propriétaire ?',
    'support.title': 'Support',
    'support.openChat': 'Ouvrir le chat',
    'support.closeChat': 'Fermer le chat',
    'support.typeHere': 'Tapez votre message ici...',
    'stats.listingsOnline': 'Logements en ligne',
    'stats.studentsRegistered': 'Étudiants inscrits',
    'stats.landlordsActive': 'Propriétaires actifs',
    'home.viewAllListings': 'Voir toutes les annonces',
    'features.landlords.title': 'Fonctionnalités pour les propriétaires',
    'features.landlords.subtitle': 'Pour les propriétaires',
    'features.landlords.lease.title': 'Bail étudiant légal avec signature électronique',
    'features.landlords.lease.desc': 'Créez et signez des baux étudiants conformes à la loi avec signature électronique sécurisée et validité juridique.',
    'features.landlords.payment.title': 'Paiement en ligne 100% sécurisé',
    'features.landlords.payment.desc': 'Recevez vos paiements en toute sécurité grâce à notre système de paiement en ligne crypté et conforme aux normes bancaires.',
    'features.landlords.inventory.title': 'État des lieux',
    'features.landlords.inventory.desc': 'Réalisez des états des lieux détaillés avec photos et signatures électroniques pour protéger votre bien.',
    'features.landlords.listings.title': 'Annonces professionnelles',
    'features.landlords.listings.desc': 'Créez des annonces attractives avec photos, vidéos et plans 3D pour valoriser votre bien immobilier.',
    'features.landlords.bookings.title': 'Gestion des réservations',
    'features.landlords.bookings.desc': 'Gérez vos demandes de réservation, acceptez ou refusez les locataires en quelques clics.',
    'features.landlords.access.title': 'Guide d\'accès',
    'features.landlords.access.desc': 'Créez des guides d\'accès personnalisés avec codes WiFi, instructions et informations pratiques.',
    'features.landlords.verification.title': 'Vérification des profils',
    'features.landlords.verification.desc': 'Tous les étudiants sont vérifiés avec leur carte étudiante INSEAD pour plus de sécurité.',
    'features.landlords.messaging.title': 'Messagerie intégrée',
    'features.landlords.messaging.desc': 'Communiquez directement avec les étudiants via notre système de messagerie sécurisé.',
    'features.landlords.stats.title': 'Statistiques détaillées',
    'features.landlords.stats.desc': 'Suivez les performances de vos annonces avec des statistiques de vues et de demandes.',
    'features.students.title': 'Fonctionnalités pour les étudiants',
    'features.students.subtitle': 'Pour les étudiants INSEAD',
    'features.students.search.title': 'Recherche avancée',
    'features.students.search.desc': 'Trouvez le logement idéal avec nos filtres avancés : prix, localisation, équipements et disponibilités.',
    'features.students.verified.title': 'Logements vérifiés',
    'features.students.verified.desc': 'Tous les propriétaires sont vérifiés pour garantir la qualité et la sécurité de votre logement.',
    'features.students.favorites.title': 'Favoris et alertes',
    'features.students.favorites.desc': 'Sauvegardez vos logements préférés et recevez des alertes pour les nouvelles annonces.',
    'features.students.booking.title': 'Réservation simple',
    'features.students.booking.desc': 'Réservez votre logement en ligne avec nos demandes de réservation sécurisées et instantanées.',
    'features.students.documents.title': 'Documents en ligne',
    'features.students.documents.desc': 'Téléchargez et gérez tous vos documents (pièce d\'identité, justificatifs) directement sur la plateforme.',
    'features.students.access.title': 'Accès facilité',
    'features.students.access.desc': 'Recevez tous les codes et instructions d\'accès dans un guide personnalisé avant votre arrivée.',
    'features.students.community.title': 'Communauté INSEAD',
    'features.students.community.desc': 'Rejoignez une communauté d\'étudiants et partagez vos expériences de logement à Fontainebleau.',
    'features.students.free.title': 'Tarification transparente',
    'features.students.free.desc': 'Tarifs clairs et transparents sans frais cachés. Payez uniquement ce qui est affiché.',
    'admin.title': 'Administration',
    'admin.subtitle': 'Tableau de bord administrateur',
    'admin.totalUsers': 'Total Utilisateurs',
    'admin.listings': 'Annonces',
    'admin.bookings': 'Réservations',
    'admin.pendingVerifications': 'Vérifications en attente',
    'admin.tabs.users': 'Utilisateurs',
    'admin.tabs.verifications': 'Vérifications',
    'admin.tabs.analytics': 'Statistiques',
    'admin.tabs.messaging': 'Messages',
    'admin.tabs.finance': 'Finances',
    'admin.tabs.pricing': 'Tarifs',
    'admin.tabs.listings': 'Annonces',
    'admin.tabs.carousel': 'Carrousel',
    'admin.tabs.stripe': 'Stripe Connect',
    'admin.tabs.settings': 'Paramètres',
    'admin.tabs.partnerOffers': 'Offres Partenaires',
    'admin.search.placeholder': 'Rechercher par email, nom, téléphone...',
    'admin.filter.allRoles': 'All roles',
    'admin.filter.allSubscriptions': 'Tous les abonnements',
    'admin.user': 'Utilisateur',
    'admin.email': 'Email',
    'admin.phone': 'Téléphone',
    'admin.role': 'Rôle',
    'admin.subscription': 'Abonnement',
    'admin.status': 'Statut',
    'admin.free': 'Gratuit',
    'admin.premium': 'Premium',
    'admin.verified': 'Vérifié',
    'admin.notVerified': 'Non soumis',
    'dashboard.landlord.title': 'Tableau de bord propriétaire',
    'dashboard.landlord.subtitle': 'Bienvenue',
    'dashboard.landlord.newListing': 'Nouvelle annonce',
    'dashboard.landlord.totalRevenue': 'Revenus totaux',
    'dashboard.landlord.pendingPayments': 'Paiements en attente',
    'dashboard.landlord.activeBookings': 'Réservations actives',
    'dashboard.landlord.pendingRequests': 'Demandes en attente',
    'dashboard.landlord.pendingRequestsSubtitle': 'Réponse recommandée dans les 24h',
    'dashboard.landlord.acceptBooking': 'Accepter',
    'dashboard.landlord.rejectBooking': 'Refuser',
    'dashboard.student.title': 'Tableau de bord étudiant',
    'dashboard.student.subtitle': 'Bienvenue',
    'dashboard.student.activeBookings': 'Réservations actives',
    'dashboard.student.favorites': 'Favoris',
    'dashboard.student.unreadMessages': 'Messages non lus',
    'dashboard.student.upcomingPayments': 'Paiements à venir',
    'dashboard.student.searchListing': 'Rechercher un logement',
    'dashboard.student.myBookings': 'Mes réservations',
    'dashboard.student.myDocuments': 'Mes documents',
    'dashboard.student.contactSupport': 'Contacter le support',
    'dashboard.student.recentBookings': 'Réservations récentes',
    'dashboard.student.upcomingPaymentsTitle': 'Paiements à venir',
    'dashboard.student.nothingDue': 'Rien à payer pour le moment',
    'dashboard.student.dueDate': 'Échéance',
    'dashboard.student.pay': 'Payer',
  },
  en: {
    'app.name': 'HELLOFONTY',
    'app.tagline': 'Free accommodation for INSEAD students in Fontainebleau',
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.favorites': 'Favorites',
    'nav.messages': 'Messages',
    'nav.myListings': 'My listings',
    'nav.addListing': 'Add listing',
    'nav.profile': 'Profile',
    'nav.signIn': 'Sign in',
    'nav.signUp': 'Sign up',
    'nav.signOut': 'Sign out',
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.firstName': 'First name',
    'auth.lastName': 'Last name',
    'auth.phone': 'Phone',
    'auth.role': 'I am',
    'auth.student': 'INSEAD Student',
    'auth.landlord': 'Landlord',
    'auth.alreadyAccount': 'Already have an account?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.signInButton': 'Sign in',
    'auth.signUpButton': 'Sign up',
    'auth.verification': 'INSEAD Verification',
    'auth.uploadDocument': 'Upload enrollment certificate (PDF)',
    'auth.pendingVerification': 'Pending verification',
    'auth.verified': 'Verified account',
    'home.hero.title': 'Find your accommodation in Fontainebleau',
    'home.hero.subtitle': 'Platform reserved for INSEAD students',
    'home.hero.verified': 'Verified housing for INSEAD students in Fontainebleau',
    'nav.pricing': 'Pricing',
    'nav.myBookingRequests': 'My requests',
    'home.hero.cta': 'Start searching',
    'home.students.title': 'Find the perfect accommodation in Fontainebleau',
    'home.landlords.title': 'Find your INSEAD tenants',
    'home.cta.title': 'Ready to get started?',
    'home.cta.subtitle': 'Join the HELLOFONTY community today',
    'home.secureplatform': '100% secure platform reserved exclusively for INSEAD students in Fontainebleau',
    'home.featured.title': 'Available housing',
    'home.featured.subtitle': 'Discover the latest listings in Fontainebleau',
    'home.map.title': 'Explore Fontainebleau',
    'home.map.subtitle': 'Discover the location of all our available accommodations',
    'home.howItWorks': 'How it works',
    'home.forStudents': 'For students',
    'home.forStudents.desc': 'Register with your INSEAD certificate, search for accommodations and contact landlords directly',
    'home.step1': 'Sign up in 30 seconds',
    'home.step2': 'Upload your enrollment certificate',
    'home.step3': 'Search for verified housing',
    'home.step4': 'Contact landlords directly',
    'home.step5': 'Book your ideal accommodation',
    'home.forLandlords': 'For landlords',
    'home.forLandlords.desc': 'Find INSEAD students with verified profiles quickly and for free',
    'home.features': 'Features',
    'home.feature.verified': 'Verified community',
    'home.feature.verified.desc': 'Access reserved for verified INSEAD students',
    'home.feature.free': '100% verified housing',
    'home.feature.free.desc': 'Reserved exclusively for verified INSEAD students',
    'home.feature.secure': 'Secure payments',
    'home.feature.secure.desc': 'All housing is verified and payments are 100% secure',
    'home.feature.direct': 'Direct contact',
    'home.feature.direct.desc': 'Integrated messaging for easy communication',
    'search.title': 'Search accommodation',
    'search.filters': 'Filters',
    'search.city': 'City',
    'search.propertyType': 'Property type',
    'search.propertyType.all': 'All',
    'search.propertyType.apartment': 'Apartment',
    'search.propertyType.house': 'House',
    'search.propertyType.room': 'Room',
    'search.propertyType.option.all': 'All types',
    'search.propertyType.option.room': 'Room',
    'search.propertyType.option.apartment': 'Apartment',
    'search.propertyType.option.house': 'House',
    'search.propertyType.option.studio': 'Studio',
    'search.priceRange': 'Max price (€/month)',
    'search.bedrooms': 'Min. bedrooms',
    'search.guests': 'Guests',
    'search.propertyTypeLabel': 'Property type',
    'search.checkIn': 'Check-in',
    'search.checkOut': 'Check-out',
    'search.guestsLabel': 'Guests',
    'search.searchButton': 'Search',
    'search.searchPlaceholder': 'Search for accommodation...',
    'search.checkInPlaceholder': 'Check-in date',
    'search.checkOutPlaceholder': 'Check-out date',
    'search.guestSingular': 'guest',
    'search.guestPlural': 'guests',
    'search.results': 'results',
    'search.noResults': 'No results found',
    'listing.perMonth': '/month',
    'listing.bedrooms': 'bedrooms',
    'listing.bathrooms': 'bathrooms',
    'listing.guests': 'max guests',
    'listing.details': 'Details',
    'listing.amenities': 'Amenities',
    'listing.availability': 'Availability',
    'listing.location': 'Location',
    'listing.available': 'available',
    'listing.availableSingular': 'available',
    'listing.singular': 'listing',
    'listing.plural': 'listings',
    'listing.contact': 'Contact landlord',
    'listing.bookingRequest': 'Send booking request',
    'listing.signInToBook': 'Sign in to book',
    'listing.addToFavorites': 'Add to favorites',
    'listing.removeFromFavorites': 'Remove from favorites',
    'listing.owner': 'Your host',
    'listing.reviews': 'reviews',
    'listing.listings': 'listings',
    'listing.listing': 'listing',
    'listing.memberSince': 'Member since',
    'listing.superhost': 'Superhost',
    'listing.verified': 'Identity verified',
    'listing.defaultBio': "Experienced host passionate about welcoming and ensuring student comfort. Always available to answer your questions and help with your housing search.",
    'listing.houseRules': 'House rules',
    'favorites.title': 'My favorites',
    'favorites.empty': 'No saved favorites',
    'messages.title': 'Messages',
    'messages.conversations': 'Conversations',
    'messages.empty': 'No messages',
    'messages.send': 'Send',
    'messages.typeMessage': 'Type your message...',
    'messages.contactAllowed': 'Booking confirmed: you can safely exchange your contact details.',
    'messages.blocked.title': 'Warning - Direct Contact Prohibited',
    'messages.blocked.attemptWarning': 'Attempt {count} - Risk of ban!',
    'messages.blocked.why': 'Why this restriction?',
    'messages.blocked.whyText': "We detected contact information in your message (phone, email, social media, etc.). For your safety and that of all users, direct exchanges outside the platform are prohibited before booking confirmation and payment.",
    'messages.blocked.risksTitle': 'Risks of going direct:',
    'messages.blocked.risk.ban': 'Risk of ban',
    'messages.blocked.risk.banDesc': 'Your account may be suspended or permanently banned',
    'messages.blocked.risk.scams': 'Fake listings and scams',
    'messages.blocked.risk.scamsDesc': 'Unable to verify authenticity without our verification',
    'messages.blocked.risk.noProtection': 'No protection',
    'messages.blocked.risk.noProtectionDesc': 'No insurance, no recourse if problems arise',
    'messages.blocked.risk.noSupport': 'No customer service or support',
    'messages.blocked.risk.noSupportDesc': 'Our team cannot help you in case of dispute',
    'messages.blocked.afterPayment': 'After confirmation and payment',
    'messages.blocked.afterPaymentText': 'Once your booking is confirmed and paid, you can freely exchange your contact details with your contact person safely.',
    'messages.blocked.modify': 'Edit my message',
    'messages.blocked.understand': 'I understand',
    'admin.alerts.title': 'Blocked Attempts',
    'admin.alerts.last7days': 'Last 7 days',
    'admin.alerts.last30days': 'Last 30 days',
    'admin.alerts.usersAtRisk': 'Users at risk',
    'admin.alerts.attemptsBlocked': 'Attempts blocked',
    'admin.alerts.totalAttempts': 'Total attempts',
    'admin.alerts.mainType': 'Main type',
    'admin.alerts.mostFrequent': 'Most frequent',
    'admin.alerts.allTypes': 'All types',
    'admin.alerts.dateTime': 'Date/Time',
    'admin.alerts.user': 'User',
    'admin.alerts.recipient': 'Recipient',
    'admin.alerts.type': 'Type',
    'admin.alerts.excerpt': 'Excerpt',
    'admin.alerts.attempts': 'Attempts',
    'admin.alerts.actions': 'Actions',
    'admin.alerts.details': 'Details',
    'admin.alerts.noAttempts': 'No blocked attempts',
    'admin.alerts.noAttemptsDesc': 'Bypass attempts will appear here',
    'admin.alerts.detailsTitle': 'Blocked Attempt Details',
    'admin.alerts.totalAttempts30': 'attempt(s) in total (last 30 days)',
    'admin.alerts.blockedContent': 'Blocked Content',
    'admin.alerts.detectedPatterns': 'Detected Patterns',
    'admin.alerts.userAtRiskTitle': 'User at Risk',
    'admin.alerts.userAtRiskDesc': 'This user has made {count} bypass attempts in the last 30 days. Monitoring recommended.',
    'admin.alerts.close': 'Close',
    'admin.alerts.dateType': 'Date & Type',
    'admin.alerts.conversations': 'Conversations',
    'admin.alerts.alertsTab': 'Alerts',
    'booking.accept': 'Accept',
    'booking.decline': 'Decline',
    'booking.contactTenant': 'Contact tenant',
    'booking.nights': 'nights',
    'booking.night': 'night',
    'myListings.title': 'My listings',
    'myListings.empty': 'No published listings',
    'myListings.add': 'Add listing',
    'myListings.edit': 'Edit',
    'myListings.delete': 'Delete',
    'addListing.title': 'Add listing',
    'addListing.title.edit': 'Edit listing',
    'addListing.basicInfo': 'Basic information',
    'addListing.title.label': 'Listing title',
    'addListing.description': 'Description',
    'addListing.propertyType': 'Property type',
    'addListing.location': 'Address and location',
    'addListing.address': 'Full address',
    'addListing.city': 'City',
    'addListing.postalCode': 'Postal code',
    'addListing.details': 'Accommodation details',
    'addListing.price': 'Price per month (€)',
    'addListing.bedrooms': 'Number of bedrooms',
    'addListing.bathrooms': 'Number of bathrooms',
    'addListing.maxGuests': 'Maximum guests',
    'addListing.amenities': 'Amenities',
    'addListing.photos': 'Photos',
    'addListing.uploadPhotos': 'Upload photos',
    'addListing.submit': 'Publish listing',
    'addListing.update': 'Update',
    'profile.title': 'My profile',
    'profile.personalInfo': 'Personal information',
    'profile.language': 'Preferred language',
    'profile.save': 'Save',
    'profile.verification': 'Verification',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Operation successful',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'footer.about': 'About',
    'footer.aboutDesc': 'HELLOFONTY is the leading platform to find student accommodation in Fontainebleau.',
    'footer.quickLinks': 'Quick links',
    'footer.searchListing': 'Search for accommodation',
    'footer.postListing': 'Post a listing',
    'footer.pricing': 'Pricing',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow us',
    'footer.rights': 'All rights reserved',
    'auth.forgotPassword': 'Forgot password?',
    'auth.forgotPasswordTitle': 'Forgot password',
    'auth.forgotPasswordSubtitle': 'Enter your email to receive a reset link',
    'auth.sendResetLink': 'Send link',
    'auth.backToSignIn': 'Back to sign in',
    'auth.emailNotFound': 'Hmm... We don\'t recognize this email! Are you sure you have an account with us? If not, now\'s the perfect time to join us!',
    'auth.resetEmailSent': 'Reset email sent successfully! The email may take 2 to 3 minutes to arrive. Don\'t forget to check your spam!',
    'auth.sending': 'Sending...',
    'auth.resetPasswordTitle': 'New password',
    'auth.resetPasswordSubtitle': 'Choose a new secure password',
    'auth.newPassword': 'New password',
    'auth.confirmPassword': 'Confirm password',
    'auth.changePassword': 'Change password',
    'auth.updating': 'Updating...',
    'auth.minCharacters': 'Minimum 6 characters',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.passwordUpdated': 'Password updated successfully! Redirecting...',
    'auth.invalidResetLink': 'Invalid or expired reset link. Please request a new one.',
    'admin.confirmDelete': 'Are you sure you want to delete this listing?',
    'admin.deleteSuccess': 'Listing deleted successfully!',
    'admin.deleteError': 'Error deleting listing',
    'admin.allRoles': 'All roles',
    'admin.students': 'Students',
    'admin.landlords': 'Landlords',
    'home.step.landlord.1': 'Create your landlord account',
    'home.step.landlord.2': 'Publish your listing with photos',
    'home.step.landlord.3': 'Receive requests from verified students',
    'home.step.landlord.4': 'Exchange directly via messaging',
    'home.step.landlord.5': 'Rent with confidence',
    'addListing.linens': 'Linens (towels and sheets)',
    'addListing.airbnbImport': 'Save time! Paste your Airbnb listing link to automatically pre-fill information.',
    'addListing.publishSuccess': 'Your listing is now live and visible to all students!',
    'myListings.confirmDuplicate': 'Duplicate this listing?',
    'myListings.duplicateSuccess': 'Listing duplicated successfully!',
    'myDocuments.fileTypeError': 'File format not accepted. Use PDF, JPG or PNG',
    'myDocuments.leaseDescription': 'The lease will be available here once signed by all parties',
    'navbar.landlordOnlyMessage': 'You must have a landlord account to post a listing.',
    'support.helpMessage': 'We are here to help you',
    'support.roleQuestion': 'Are you a student or a landlord?',
    'support.title': 'Support',
    'support.openChat': 'Open chat',
    'support.closeChat': 'Close chat',
    'support.typeHere': 'Type your message here...',
    'stats.listingsOnline': 'Listings online',
    'stats.studentsRegistered': 'Registered students',
    'stats.landlordsActive': 'Active landlords',
    'home.viewAllListings': 'View all listings',
    'features.landlords.title': 'Features for landlords',
    'features.landlords.subtitle': 'For landlords',
    'features.landlords.lease.title': 'Legal student lease with electronic signature',
    'features.landlords.lease.desc': 'Create and sign legally compliant student leases with secure electronic signature and legal validity.',
    'features.landlords.payment.title': '100% secure online payment',
    'features.landlords.payment.desc': 'Receive your payments securely through our encrypted online payment system that complies with banking standards.',
    'features.landlords.inventory.title': 'Property inventory',
    'features.landlords.inventory.desc': 'Conduct detailed property inventories with photos and electronic signatures to protect your property.',
    'features.landlords.listings.title': 'Professional listings',
    'features.landlords.listings.desc': 'Create attractive listings with photos, videos and 3D floor plans to showcase your property.',
    'features.landlords.bookings.title': 'Booking management',
    'features.landlords.bookings.desc': 'Manage your booking requests, accept or decline tenants with just a few clicks.',
    'features.landlords.access.title': 'Access guide',
    'features.landlords.access.desc': 'Create personalized access guides with WiFi codes, instructions and practical information.',
    'features.landlords.verification.title': 'Profile verification',
    'features.landlords.verification.desc': 'All students are verified with their INSEAD student ID for added security.',
    'features.landlords.messaging.title': 'Integrated messaging',
    'features.landlords.messaging.desc': 'Communicate directly with students through our secure messaging system.',
    'features.landlords.stats.title': 'Detailed statistics',
    'features.landlords.stats.desc': 'Track your listings performance with view and request statistics.',
    'features.students.title': 'Features for students',
    'features.students.subtitle': 'For INSEAD students',
    'features.students.search.title': 'Advanced search',
    'features.students.search.desc': 'Find the ideal accommodation with our advanced filters: price, location, amenities and availability.',
    'features.students.verified.title': 'Verified housing',
    'features.students.verified.desc': 'All landlords are verified to ensure the quality and safety of your accommodation.',
    'features.students.favorites.title': 'Favorites and alerts',
    'features.students.favorites.desc': 'Save your favorite accommodations and receive alerts for new listings.',
    'features.students.booking.title': 'Simple booking',
    'features.students.booking.desc': 'Book your accommodation online with our secure and instant booking requests.',
    'features.students.documents.title': 'Online documents',
    'features.students.documents.desc': 'Upload and manage all your documents (ID, proof of income) directly on the platform.',
    'features.students.access.title': 'Easy access',
    'features.students.access.desc': 'Receive all codes and access instructions in a personalized guide before your arrival.',
    'features.students.community.title': 'INSEAD community',
    'features.students.community.desc': 'Join a community of students and share your housing experiences in Fontainebleau.',
    'features.students.free.title': 'Transparent pricing',
    'features.students.free.desc': 'Clear and transparent rates with no hidden fees. Pay only what is displayed.',
    'admin.title': 'Administration',
    'admin.subtitle': 'Administrator dashboard',
    'admin.totalUsers': 'Total Users',
    'admin.listings': 'Listings',
    'admin.bookings': 'Bookings',
    'admin.pendingVerifications': 'Pending verifications',
    'admin.tabs.users': 'Users',
    'admin.tabs.verifications': 'Verifications',
    'admin.tabs.analytics': 'Analytics',
    'admin.tabs.messaging': 'Messages',
    'admin.tabs.finance': 'Finance',
    'admin.tabs.pricing': 'Pricing',
    'admin.tabs.listings': 'Listings',
    'admin.tabs.carousel': 'Carousel',
    'admin.tabs.stripe': 'Stripe Connect',
    'admin.tabs.settings': 'Settings',
    'admin.tabs.partnerOffers': 'Partner Offers',
    'admin.search.placeholder': 'Search by email, name, phone...',
    'admin.filter.allRoles': 'All roles',
    'admin.filter.allSubscriptions': 'All subscriptions',
    'admin.user': 'User',
    'admin.email': 'Email',
    'admin.phone': 'Phone',
    'admin.role': 'Role',
    'admin.subscription': 'Subscription',
    'admin.status': 'Status',
    'admin.free': 'Free',
    'admin.premium': 'Premium',
    'admin.verified': 'Verified',
    'admin.notVerified': 'Not submitted',
    'dashboard.landlord.title': 'Landlord dashboard',
    'dashboard.landlord.subtitle': 'Welcome',
    'dashboard.landlord.newListing': 'New listing',
    'dashboard.landlord.totalRevenue': 'Total revenue',
    'dashboard.landlord.pendingPayments': 'Pending payments',
    'dashboard.landlord.activeBookings': 'Active bookings',
    'dashboard.landlord.pendingRequests': 'Pending requests',
    'dashboard.landlord.pendingRequestsSubtitle': 'Response recommended within 24h',
    'dashboard.landlord.acceptBooking': 'Accept',
    'dashboard.landlord.rejectBooking': 'Reject',
    'dashboard.student.title': 'Student dashboard',
    'dashboard.student.subtitle': 'Welcome',
    'dashboard.student.activeBookings': 'Active bookings',
    'dashboard.student.favorites': 'Favorites',
    'dashboard.student.unreadMessages': 'Unread messages',
    'dashboard.student.upcomingPayments': 'Upcoming payments',
    'dashboard.student.searchListing': 'Search for housing',
    'dashboard.student.myBookings': 'My bookings',
    'dashboard.student.myDocuments': 'My documents',
    'dashboard.student.contactSupport': 'Contact support',
    'dashboard.student.recentBookings': 'Recent bookings',
    'dashboard.student.upcomingPaymentsTitle': 'Upcoming payments',
    'dashboard.student.nothingDue': 'Nothing due at the moment',
    'dashboard.student.dueDate': 'Due date',
    'dashboard.student.pay': 'Pay',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { profile, updateProfile } = useAuth();
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    if (profile?.preferred_language) {
      setLanguageState(profile.preferred_language);
    }
  }, [profile]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (profile) {
      await updateProfile({ preferred_language: lang });
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const translateFeature = (feature: string): string => {
    if (!feature.includes(' / ')) {
      return feature;
    }
    const [fr, en] = feature.split(' / ');
    return language === 'fr' ? fr : en;
  };

  const value = {
    language,
    setLanguage,
    t,
    translateFeature,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
