CREATE OR REPLACE FUNCTION public.is_landlord()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public', 'pg_temp'
AS $$ SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'landlord'); $$;

CREATE OR REPLACE FUNCTION public.is_student()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public', 'pg_temp'
AS $$ SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'student'); $$;

GRANT EXECUTE ON FUNCTION public.is_landlord() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_student() TO authenticated;

DROP POLICY IF EXISTS "Les admins peuvent supprimer des critères de comparaison" ON agency_comparison_features;
CREATE POLICY "Les admins peuvent supprimer des critères de comparaison" ON agency_comparison_features FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Les admins peuvent insérer des critères de comparaison" ON agency_comparison_features;
CREATE POLICY "Les admins peuvent insérer des critères de comparaison" ON agency_comparison_features FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Les admins peuvent modifier des critères de comparaison" ON agency_comparison_features;
CREATE POLICY "Les admins peuvent modifier des critères de comparaison" ON agency_comparison_features FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all blocked messages" ON blocked_messages;
CREATE POLICY "Admins can view all blocked messages" ON blocked_messages FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can manage categories" ON blog_categories;
CREATE POLICY "Admins can manage categories" ON blog_categories FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can manage post tags" ON blog_post_tags;
CREATE POLICY "Admins can manage post tags" ON blog_post_tags FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can delete posts" ON blog_posts;
CREATE POLICY "Admins can delete posts" ON blog_posts FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can insert posts" ON blog_posts;
CREATE POLICY "Admins can insert posts" ON blog_posts FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all posts" ON blog_posts;
CREATE POLICY "Admins can view all posts" ON blog_posts FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update all posts" ON blog_posts;
CREATE POLICY "Admins can update all posts" ON blog_posts FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can manage tags" ON blog_tags;
CREATE POLICY "Admins can manage tags" ON blog_tags FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all bookings" ON bookings;
CREATE POLICY "Admins can view all bookings" ON bookings FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update bookings" ON bookings;
CREATE POLICY "Admins can update bookings" ON bookings FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Les admins peuvent supprimer des comparaisons" ON comparison_items;
CREATE POLICY "Les admins peuvent supprimer des comparaisons" ON comparison_items FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Les admins peuvent insérer des comparaisons" ON comparison_items;
CREATE POLICY "Les admins peuvent insérer des comparaisons" ON comparison_items FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Les admins peuvent modifier des comparaisons" ON comparison_items;
CREATE POLICY "Les admins peuvent modifier des comparaisons" ON comparison_items FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "admin_delete_contract_template_sections" ON contract_template_sections;
CREATE POLICY "admin_delete_contract_template_sections" ON contract_template_sections FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "admin_insert_contract_template_sections" ON contract_template_sections;
CREATE POLICY "admin_insert_contract_template_sections" ON contract_template_sections FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "admin_update_contract_template_sections" ON contract_template_sections;
CREATE POLICY "admin_update_contract_template_sections" ON contract_template_sections FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can manage element templates" ON default_element_templates;
CREATE POLICY "Admins can manage element templates" ON default_element_templates FOR ALL TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can manage room templates" ON default_room_templates;
CREATE POLICY "Admins can manage room templates" ON default_room_templates FOR ALL TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "select_admin_deposits" ON deposit_transactions;
CREATE POLICY "select_admin_deposits" ON deposit_transactions FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can delete FAQs" ON faqs;
CREATE POLICY "Admins can delete FAQs" ON faqs FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can insert FAQs" ON faqs;
CREATE POLICY "Admins can insert FAQs" ON faqs FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can update FAQs" ON faqs;
CREATE POLICY "Admins can update FAQs" ON faqs FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Étudiants peuvent ajouter des favoris" ON favorites;
CREATE POLICY "Étudiants peuvent ajouter des favoris" ON favorites FOR INSERT TO authenticated WITH CHECK (((auth.uid() = student_id) AND is_student()));
DROP POLICY IF EXISTS "Admins can delete features" ON feature_carousel_images;
CREATE POLICY "Admins can delete features" ON feature_carousel_images FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can insert features" ON feature_carousel_images;
CREATE POLICY "Admins can insert features" ON feature_carousel_images FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Public views active, admins view all" ON feature_carousel_images;
CREATE POLICY "Public views active, admins view all" ON feature_carousel_images FOR SELECT TO public USING (((is_active = true) OR is_admin()));
DROP POLICY IF EXISTS "Admins can update features" ON feature_carousel_images;
CREATE POLICY "Admins can update features" ON feature_carousel_images FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admin can insert invoices" ON invoices;
CREATE POLICY "Admin can insert invoices" ON invoices FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admin can view all invoices" ON invoices;
CREATE POLICY "Admin can view all invoices" ON invoices FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can view all landlord documents" ON landlord_documents;
CREATE POLICY "Admins can view all landlord documents" ON landlord_documents FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update landlord document status" ON landlord_documents;
CREATE POLICY "Admins can update landlord document status" ON landlord_documents FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "admin_insert_subscription_charges" ON landlord_subscription_charges;
CREATE POLICY "admin_insert_subscription_charges" ON landlord_subscription_charges FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "admin_read_subscription_charges" ON landlord_subscription_charges;
CREATE POLICY "admin_read_subscription_charges" ON landlord_subscription_charges FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "admin_update_subscription_charges" ON landlord_subscription_charges;
CREATE POLICY "admin_update_subscription_charges" ON landlord_subscription_charges FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can do everything with leases" ON leases;
CREATE POLICY "Admins can do everything with leases" ON leases FOR ALL TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Landlords can create leases" ON leases;
CREATE POLICY "Landlords can create leases" ON leases FOR INSERT TO authenticated WITH CHECK (((landlord_id = auth.uid()) AND is_landlord()));
DROP POLICY IF EXISTS "Admins peuvent supprimer toutes les images" ON listing_images;
CREATE POLICY "Admins peuvent supprimer toutes les images" ON listing_images FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins peuvent ajouter des images" ON listing_images;
CREATE POLICY "Admins peuvent ajouter des images" ON listing_images FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins peuvent voir toutes les images" ON listing_images;
CREATE POLICY "Admins peuvent voir toutes les images" ON listing_images FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins peuvent modifier toutes les images" ON listing_images;
CREATE POLICY "Admins peuvent modifier toutes les images" ON listing_images FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins peuvent supprimer toutes les annonces" ON listings;
CREATE POLICY "Admins peuvent supprimer toutes les annonces" ON listings FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Propriétaires peuvent créer des annonces" ON listings;
CREATE POLICY "Propriétaires peuvent créer des annonces" ON listings FOR INSERT TO authenticated WITH CHECK (((auth.uid() = landlord_id) AND is_landlord()));
DROP POLICY IF EXISTS "Admins peuvent voir toutes les annonces" ON listings;
CREATE POLICY "Admins peuvent voir toutes les annonces" ON listings FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins peuvent modifier toutes les annonces" ON listings;
CREATE POLICY "Admins peuvent modifier toutes les annonces" ON listings FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins peuvent voir tous les messages" ON messages;
CREATE POLICY "Admins peuvent voir tous les messages" ON messages FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can delete partner offers" ON partner_offers;
CREATE POLICY "Admins can delete partner offers" ON partner_offers FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can insert partner offers" ON partner_offers;
CREATE POLICY "Admins can insert partner offers" ON partner_offers FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all partner offers" ON partner_offers;
CREATE POLICY "Admins can view all partner offers" ON partner_offers FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update partner offers" ON partner_offers;
CREATE POLICY "Admins can update partner offers" ON partner_offers FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Only admins can update platform settings" ON platform_settings;
CREATE POLICY "Only admins can update platform settings" ON platform_settings FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can delete pricing plans" ON pricing_plans;
CREATE POLICY "Admins can delete pricing plans" ON pricing_plans FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can create pricing plans" ON pricing_plans;
CREATE POLICY "Admins can create pricing plans" ON pricing_plans FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all pricing plans" ON pricing_plans;
CREATE POLICY "Admins can view all pricing plans" ON pricing_plans FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update pricing plans" ON pricing_plans;
CREATE POLICY "Admins can update pricing plans" ON pricing_plans FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins peuvent modifier tous les profils" ON profiles;
CREATE POLICY "Admins peuvent modifier tous les profils" ON profiles FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can manage all inventories" ON property_inventories;
CREATE POLICY "Admins can manage all inventories" ON property_inventories FOR ALL TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "admins_can_read_refunds" ON refunds;
CREATE POLICY "admins_can_read_refunds" ON refunds FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can delete rent payments" ON rent_payments;
CREATE POLICY "Admins can delete rent payments" ON rent_payments FOR DELETE TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can view all rent payments" ON rent_payments;
CREATE POLICY "Admins can view all rent payments" ON rent_payments FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update rent payments" ON rent_payments;
CREATE POLICY "Admins can update rent payments" ON rent_payments FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins manage rent reminder settings" ON rent_reminder_settings;
CREATE POLICY "Admins manage rent reminder settings" ON rent_reminder_settings FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admin can view all stripe customers" ON stripe_customers;
CREATE POLICY "Admin can view all stripe customers" ON stripe_customers FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admin can view all stripe subscriptions" ON stripe_subscriptions;
CREATE POLICY "Admin can view all stripe subscriptions" ON stripe_subscriptions FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can view all student documents" ON student_documents;
CREATE POLICY "Admins can view all student documents" ON student_documents FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update student document status" ON student_documents;
CREATE POLICY "Admins can update student document status" ON student_documents FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admin can view all subscriptions" ON subscriptions;
CREATE POLICY "Admin can view all subscriptions" ON subscriptions FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admin can update all subscriptions" ON subscriptions;
CREATE POLICY "Admin can update all subscriptions" ON subscriptions FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all conversations" ON support_conversations;
CREATE POLICY "Admins can view all conversations" ON support_conversations FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Admins can update all conversations" ON support_conversations;
CREATE POLICY "Admins can update all conversations" ON support_conversations FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can send messages in any conversation" ON support_messages;
CREATE POLICY "Admins can send messages in any conversation" ON support_messages FOR INSERT TO authenticated WITH CHECK (((auth.uid() = sender_id) AND (sender_type = 'admin'::text) AND is_admin()));
DROP POLICY IF EXISTS "Admins can view all messages" ON support_messages;
CREATE POLICY "Admins can view all messages" ON support_messages FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "Users can view messages by conversation" ON support_messages;
CREATE POLICY "Users can view messages by conversation" ON support_messages FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM support_conversations WHERE ((support_conversations.id = support_messages.conversation_id) AND ((support_conversations.user_id = auth.uid()) OR (support_conversations.user_id IS NULL) OR is_admin())))));
DROP POLICY IF EXISTS "Admins can update all messages" ON support_messages;
CREATE POLICY "Admins can update all messages" ON support_messages FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "Admins can view all tasks" ON tasks;
CREATE POLICY "Admins can view all tasks" ON tasks FOR SELECT TO authenticated USING (is_admin());

REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON profiles FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON bookings FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON listings FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON rent_payments FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON subscriptions FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON messages FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON leases FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON listing_images FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON landlord_stripe_accounts FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON deposit_transactions FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON landlord_documents FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON student_documents FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON property_inventories FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON invoices FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON refunds FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON stripe_customers FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON stripe_subscriptions FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON landlord_subscription_charges FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON rent_reminder_settings FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON contract_template_sections FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON blocked_messages FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON tasks FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON notifications FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON favorites FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON access_guides FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON access_guide_unlock_overrides FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON external_ical_feeds FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON imported_blocked_dates FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON blocked_dates FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON feature_carousel_images FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON blog_posts FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON blog_categories FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON blog_tags FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON blog_post_tags FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON faqs FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON pricing_plans FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON partner_offers FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON platform_settings FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON agency_comparison_features FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON comparison_items FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON default_element_templates FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON default_room_templates FROM anon;
